// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngijsizuaxifqnjhbkuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5naWpzaXp1YXhpZnFuamhia3V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTg3MDAsImV4cCI6MjA2MjczNDcwMH0.CjN1GoxK2QQW5eDXcS7qISMdQv1Zacn6ly0NJ_CTe9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});